"""orcamento: preferencias, regras aprendidas, jobs

Revision ID: 2e24db9eb765
Revises: 85c1fedfb7c5
Create Date: 2026-08-31 16:11:14.913282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2e24db9eb765'
down_revision: Union[str, None] = '85c1fedfb7c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preferencias_globais',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('configuracao', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_table('orcamento_jobs',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('projeto_id', sa.UUID(), nullable=True),
    sa.Column('arquivo_origem', sa.String(length=500), nullable=False),
    sa.Column('status', sa.Enum('processando', 'aguardando_revisao', 'confirmado', 'erro', name='statusorcamentojob'), nullable=False),
    sa.Column('ambientes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avisos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regras_aprendidas',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('instrucao_original', sa.Text(), nullable=False),
    sa.Column('regra_normalizada', sa.Text(), nullable=False),
    sa.Column('origem_job_id', sa.UUID(), nullable=True),
    sa.Column('origem_modulo_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['origem_job_id'], ['orcamento_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('regras_aprendidas')
    op.drop_table('orcamento_jobs')
    op.drop_table('preferencias_globais')
    op.execute("DROP TYPE IF EXISTS statusorcamentojob")
    # ### end Alembic commands ###
