"""producao: tarefas_cronograma, ausencias_operador, campos de operador/kanban

Revision ID: a4070003c6c5
Revises: e92ea3dc0a3e
Create Date: 2026-09-03 14:08:29.928675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a4070003c6c5'
down_revision: Union[str, None] = 'e92ea3dc0a3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ausencias_operador',
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('motivo', sa.String(length=300), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tarefas_cronograma',
    sa.Column('projeto_id', sa.UUID(), nullable=False),
    sa.Column('operador_id', sa.UUID(), nullable=True),
    sa.Column('predecessora_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('tipo_vinculo', sa.Enum('FS', 'SS', name='tipovinculo'), nullable=False),
    sa.Column('lag_dias', sa.Integer(), nullable=False),
    sa.Column('duracao_dias', sa.Integer(), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_fim', sa.Date(), nullable=False),
    sa.Column('baseline_inicio', sa.Date(), nullable=True),
    sa.Column('baseline_fim', sa.Date(), nullable=True),
    sa.Column('percentual_concluido', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('nao_iniciada', 'em_andamento', 'concluida', 'bloqueada', 'atrasada', 'em_risco', name='statustarefa'), nullable=False),
    sa.Column('folga', sa.Integer(), nullable=False),
    sa.Column('eh_caminho_critico', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('historico', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['operador_id'], ['usuarios.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['predecessora_id'], ['tarefas_cronograma.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['projeto_id'], ['projetos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # add_column (ao contrario de create_table) nao cria o tipo ENUM
    # sozinho -- precisa criar explicitamente antes de usar.
    statusproducao_enum = postgresql.ENUM(
        'backlog', 'planejamento', 'em_producao', 'acabamento', 'qualidade', 'concluido',
        name='statusproducao',
    )
    statusproducao_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('projetos', sa.Column('status_producao', statusproducao_enum, nullable=True))
    op.add_column('projetos', sa.Column('cor', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('especialidades', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('usuarios', sa.Column('cor', sa.String(length=20), nullable=True))
    op.add_column('usuarios', sa.Column('capacidade_diaria', sa.Float(), nullable=True))
    op.add_column('usuarios', sa.Column('dias_trabalho', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'dias_trabalho')
    op.drop_column('usuarios', 'capacidade_diaria')
    op.drop_column('usuarios', 'cor')
    op.drop_column('usuarios', 'especialidades')
    op.drop_column('projetos', 'cor')
    op.drop_column('projetos', 'status_producao')
    postgresql.ENUM(name='statusproducao').drop(op.get_bind(), checkfirst=True)
    op.drop_table('tarefas_cronograma')
    op.drop_table('ausencias_operador')
    # ### end Alembic commands ###
